import Head from 'next/head'
import Image from 'next/image'
import { ReactElement, useState } from 'react'
import styles from '../styles/Home.module.css'
import Soporte from './Soporte'

export default function Home(): ReactElement {

  const [tickets, setTickets]: any = useState([])

  return (
    <div className={styles.container}>
      <Head>
        <title>PSA App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          PSA - Modulo Soporte
        </h1>

        <Soporte tickets={tickets} setTickets={setTickets}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
